export const defProducts: {
    _id: string | number,
    name: string,
    category: string,
    description: string,
    unit: string,
    img?: string,
    price: number,
  }[] = [
    {
      _id: 1,
      name: "product 1",
      category: "category 1",
      description: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium",
      unit: "1KG",
      img: "product_default.jpg",
      price: 50,
    },
    {
      _id: 2,
      name: "product 2",
      category: "category 2",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      unit: "500g",
      img: "product_default.jpg",
      price: 30,
    },
    {
      _id: 3,
      name: "product 3",
      category: "category 1",
      description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      unit: "2KG",
      img: "product_default.jpg",
      price: 70,
    },
    {
      _id: 4,
      name: "product 4",
      category: "category 3",
      description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      unit: "750g",
      img: "product_default.jpg",
      price: 45,
    },
    {
      _id: 5,
      name: "product 5",
      category: "category 2",
      description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      unit: "1.5KG",
      img: "product_default.jpg",
      price: 60,
    },
    {
      _id: 6,
      name: "product 6",
      category: "category 3",
      description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
      unit: "800g",
      img: "product_default.jpg",
      price: 40,
    },
    {
      _id: 7,
      name: "product 7",
      category: "category 1",
      description: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
      unit: "1.2KG",
      img: "product_default.jpg",
      price: 55,
    },
    {
      _id: 8,
      name: "product 8",
      category: "category 2",
      description: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
      unit: "900g",
      img: "product_default.jpg",
      price: 65,
    },
    {
      _id: 9,
      name: "product 9",
      category: "category 3",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      unit: "1.8KG",
      img: "product_default.jpg",
      price: 75,
    },
    {
      _id: 10,
      name: "product 10",
      category: "category 1",
      description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      unit: "1.5KG",
      img: "product_default.jpg",
      price: 55,
    },
  ];
  